import type { NextPage } from 'next'
import Head from 'next/head'
import { About } from '../src/about'
import { Footer } from '../src/footer'

const AboutPage: NextPage = () => {
  return (
    <div>
      <Head>
        <title>AE Studio - Challenge About</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <About />

      <Footer />
    </div>
  )
}

export default AboutPage
