import type { NextPage } from 'next'
import Head from 'next/head'
import { Footer } from '../src/footer'
import { Home } from '../src/home'

const HomePage: NextPage = () => {
  return (
    <div>
      <Head>
        <title>AE Studio - Challenge</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Home />

      <Footer />
    </div>
  )
}

export default HomePage
